version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    networks:
      - inditex_network
    restart: always

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: inditex             
      MYSQL_PASSWORD: root                   
      MYSQL_ROOT_PASSWORD: root              
    ports:
      - "3306:3306"                          
    networks:
      - inditex_network
    restart: always

networks:
  inditex_network:
    driver: bridge